overview:
  title: Fly Out Zoom
  image: logo.png
  description: Shows how a product detail page could look with hover zoom used.
  facts:
    - Hover zoom
    - Enabling zoom by CSS class
  order: 2
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/furniture-menu.yml
      featured:
        template: data/furniture-featured.yml
      highlight: DEAL OF THE DAY
      footer:
        credits:
          photos:
            author: various artists
            link: https://pixabay.com/
            platform: Pixabay
          viewer:
            link: https://www.neptunelabs.com/fsi-quickzoom/
      fsi:
        touchZoom: true
        quickZoom: true
      bootstrap:
        icons: false
  mapping:
    html: "index.html"
    css: "flyout.css"
    js: "flyout.js"
jsfiddle:
  deploy: true
