overview:
  title: Fly Out Zoom
  image: logo.png
  description: Shows how a product detail page could look with hover zoom used.
  order: 2
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/furniture-menu.yml
      featured:
        template: data/furniture-featured.yml
      highlight: DEAL OF THE DAY
      footer: true
      fsi:
        touchZoom: true
        quickZoom: true
      bootstrap:
        icons: false
  mapping:
    html: "index.html"
    css: "flyout.css"
    js: "flyout.js"
jsfiddle:
  deploy: true
