overview:
  title: Fly Out Zoom
  image: logo.png
  description: Shows how a product detail page would look with hover zoom used.
  facts:
    - Hover zoom
    - Enabling hover zoom by CSS class
  order: 2
schema: bootstrap-taupe
sample:
  menu:
    data: furniture-menu.yml
  featured:
    data: furniture-featured.yml
  highlight: DEAL OF THE DAY
  footer:
    credits:
      photos:
        author: various artists
        link: https://pixabay.com/
        platform: Pixabay
      viewer:
        link: https://www.neptunelabs.com/fsi-quickzoom/
  fsi:
    touchZoom: true
    quickZoom: true
  bootstrap:
    icons: false
